step_converter:
	arduino-cli compile -b arduino:mbed_nano:nano33ble --build-path .compiledb examples/step-boost-converter/step-boost-converter.ino

pid_converter:
	arduino-cli compile -b arduino:mbed_nano:nano33ble --build-path .compiledb examples/pid-boost-converter/pid-boost-converter.ino
